### ISSUE TITLE
XML Commont not always correctly formated

### ISSUE THREAD

**Issue by nielsNocore** [earloc/TypealizR#206]
in come cases the added xml comments in the <summary> are not correctly formated: 
we use some analysers like stylecop, sonarqube and despite the auto-generate tag these analyzers show warnings. 

<img width="1099" alt="image" src="https://github.com/earloc/TypealizR/assets/122032239/02f81a48-acd8-437d-9d0d-104a60e24554">

due to the use of &lt and n&gt this result in 4 differnent warnings when compiling. 

missing xml coments on the generated class.. 
![image](https://github.com/earloc/TypealizR/assets/122032239/cc9bd0e2-4eaa-4d12-ba9d-551dae4ca557)

**Comment by earloc** [comment]
Could you post the messages emitted by the external analyzers?

How would the "comiant" version look in your example?

Might be an easy fix.

**Comment by nielsNocore** [comment]
hi there,
here are the error messages in visual studio
![image](https://github.com/earloc/TypealizR/assets/122032239/db892649-9ac1-4789-92b7-b11d4e70a997)

and 
![image](https://github.com/earloc/TypealizR/assets/122032239/ce08f356-a51f-4a74-84e3-1d8d7d38184b)

we also generate some docus using DocFX and due to there warnings we also get warnings from docfx like: 
![image](https://github.com/earloc/TypealizR/assets/122032239/18c74c98-f26c-4fc8-94ee-520de981a497)

**Comment by nielsNocore** [comment]
also in the the typelizedClassSourceGenerator files there are some errors on public methods that do not have a SML comment
![image](https://github.com/earloc/TypealizR/assets/122032239/69936ab3-3956-44c0-93c0-5a08d728cc69)
and 
![image](https://github.com/earloc/TypealizR/assets/122032239/2e970388-a6a6-4f45-a3c9-5df70ef7648b)

**Comment by earloc** [comment]
Ok, thx. Will have a look into that when I find the time.

Would it also help, if you could opt-out of TypealizR generating those comment? Or would the analyzers then complain about non-documented public members?

**Comment by earloc** [comment]
ahh, missed the second example 😇. Opting-out would probably not work for you.

**Comment by nielsNocore** [comment]
no indeed, opoing-out would not work for us 😄

**Comment by earloc** [comment]
[v0.9.6](https://github.com/earloc/TypealizR/releases/tag/v0.9.6) should arrive, shortly.

Hoping I catched all occurences

**Comment by earloc** [comment]
@nielsNocore let me know of 0.9.6 fixes all of your issues.

Just reopen this issue if not and provide some details what might be still missing.

**Comment by nielsNocore** [comment]
@earloc thanks did a try, found some isssues, 
created a PR #208 to fix this,.

**Comment by earloc** [comment]
@nielsNocore 

[v0.9.7-pre01](https://github.com/earloc/TypealizR/releases/tag/v0.9.7-pre01) should arrive soon-ish

**Comment by earloc** [comment]
https://www.nuget.org/packages/TypealizR/0.9.7-pre0001

@nielsNocore let me know if this is working for you now.

**Comment by nielsNocore** [comment]
we are getting there 😄 
have some remaining issues:
the see ref is nog valid now is missing the {} after IStringLocalizer.
![image](https://github.com/earloc/TypealizR/assets/122032239/a4959b8e-a24a-4f46-bdb4-47f6d81f2e2a)
and
![image](https://github.com/earloc/TypealizR/assets/122032239/d9066938-4593-4ba1-9335-bb8b2a0b9524)
i think the attribute should be placed after the summary. 


and i found a new one:
with the resource key: "[Tax]: Net" 
the following code is generated:
![image](https://github.com/earloc/TypealizR/assets/122032239/8ab4b40f-7b60-43d2-846f-b763ee1159bf)

**Comment by nielsNocore** [comment]
created a new PR with a proposal: #210. 

let me know what you think

**Comment by earloc** [comment]
Seems ok, thx for the contribution.

The whole "template" - stuff would need a major rewrite (see #65) , so I'm totally fine with whatever you need to do in order to get rid of your issues.

Sadly, the PR-build somehow fails while beginning SonatCloud-Analysis. Always a pita with this thingy 😅.

Having some other code-smells to tackle, which I'm planning to fix by the end of the week. In the mean-time, I could publish another pre-version based on this PRs branch.

**Comment by nielsNocore** [comment]
i tried version 0.9.7-pre0003, as far as ik can see, al the issues are resolved!

**Comment by earloc** [comment]
nice. I initiated publish of non-pre version of v0.9.7.

Feel free to come back, if anything else might pop up.

And again, thx for your contribution 👊.

**Comment by nielsNocore** [comment]
thank you for your help with this. 
i really like this packages, so keep up the good work! 💪

**Comment by earloc** [comment]
You're welcome.

Always nice to get in touch with someone  benefitting from a certain effort 🙃.

v0.9.9 is out, might perform slightly better (according to SonarCloud, at least) ✌️.
