### ISSUE TITLE
Support for Portable Object format

### ISSUE THREAD

**Issue by dodyg** [earloc/TypealizR#29]
Please combine this with Portable Object support (https://www.nuget.org/packages/OrchardCore.Localization/). It is so much nicer than RESX.

**Comment by earloc** [comment]
I´d love to get a deeper dive into that topic. To further assist in a possible adoption, would you be so kind and provide details about what you´d expect from `TypealizR` once support has been implemented?
Would be great also if you could provide a sample-project and describe the behaivor once `TypealizR` ran on such a sample.

**Comment by dodyg** [comment]
These are two sample projects that use `OrchardCore.Localization`.
- https://github.com/dodyg/practical-aspnetcore/blob/net6.0/projects/localization/localization-5
- https://github.com/dodyg/practical-aspnetcore/blob/net6.0/projects/localization/localization-6
